### ISSUE TITLE
Add space after each object

### ISSUE THREAD

**Issue by vinodkolla** [jeremyfa/yaml.js#110]
I am using yaml-js to auto-format the yaml files. I have a big JSON file with chunks of objects in it. When i convert them to YAML format, i want to add space after each json object. Example:
```
{
  person1: {
    name: "Foo"
  },
  person2: {
     name: "Bar"
  }
}
```
When this is converted to YAML, it formats as 
```
person1:
    name: "Foo"
person2:
   name: "Bar"
```
Expected output is :
```
person1:
    name: "Foo"

person2:
   name: "Bar"
```
