### ISSUE TITLE
How to format YAML?

### ISSUE THREAD

**Issue by lijialiang** [jeremyfa/yaml.js#115]
e.g.

```yaml
name: xxx
version: 0.0.1
object:
    a: 1
    b: 2
array: 
    - 1
    - 2
```

to

```yaml
name: xxx

version: 0.0.1

object:
    a: 1
    b: 2

array: 
    - 1
    - 2
```
