### ISSUE TITLE
Format array of objects

### ISSUE THREAD

**Issue by YarovoiVadym** [jeremyfa/yaml.js#117]
This object: 

```
[
    {
        name: 'name',
        value: 'value'
    },
    {
        name: 'name',
        value: 'value'
    },
    {
        name: 'name',
        valueFrom: {
            name: 'value',
            key: ''
        }
    }
]
```

After YAML.stringify I expect this: 

```
- name: name
  value: value
- name: name
  value: value
- name: name
  valueFrom:
      name: value
      key: ""
```

but instead of expected result I get this:

```
-
   name: name
   value: value
-
   name: name
   value: value
-
   name: name
   valueFrom:
     name: value
     key: ""
```

It's not right YAML formatting
