### ISSUE TITLE
breaks on yml which yamllint.com says is valid

### ISSUE THREAD

**Issue by coolaj86** [jeremyfa/yaml.js#12]
YAMLLint.com says this is valid:

``` yaml

---
  foo: "bar"
  baz: 
    - "qux"
    - "quxx"
  corge: null
  grault: 1
  garply: true
  waldo: "false"
  fred: "undefined"
  emptyArray: []
  emptyObject: {}
  emptyString: ""
```

yamljs says

```
{ message: "Unable to parse."
, parsedFile: null
, parsedLine: 2
, rawMessage: "Unable to parse."
, snippet: "  foo: \"bar\""
}
```

I don't know which is telling the truth.
