### ISSUE TITLE
doesn't process compact (anything)

### ISSUE THREAD

**Issue by sfinktah** [jeremyfa/yaml.js#137]
This is valid YAML 
```yaml
- just: write some
- yaml: 
  - [here, and]
  - {it: updates, in: real-time}
- - This is a sequence
  - inside another sequence
```

Your code renders it as
```json
[{"just":"write some"},{"yaml":[["here","and"],{"it":"updates","in":"real-time"}]},"- This is a sequence\n- inside another sequence"]
```
