### ISSUE TITLE
feature: ENV-Variable support would be awesome

### ISSUE THREAD

**Issue by typoworx-de** [jeremyfa/yaml.js#142]
I'm rarely searching for a node-yaml parser that can handle env-variables and variable-substitutes:

```yaml
myvar: bar

config:
   foo1: ${bar}
   foo2: ${env: MY_GLOBAL_VAR}
```

Demo:
```MY_GLOBAL_VAR=Hello node .```

resulting in:

```Object
{
    myvar: "bar"
    config: {
        foo1: "bar"
        foo2: "Hello"
    }
}
```
