### ISSUE TITLE
YAML output incorrect for expanded empty dict (JSON object)

### ISSUE THREAD

**Issue by thomscode** [jeremyfa/yaml.js#59]
Given the following JSON object:

``` json
{
    "emptyArray": [],
    "fullArray": [1, 2, 3],
    "emptyObject": {},
    "fullObject": {
        "key": "value"
    },
    "integer": 7,
    "string": "hello World!"
}
```

if I use `YAML.stringify(data, 1, 4);` I get the following output:

``` yaml
emptyArray: []
fullArray: [1, 2, 3]
emptyObject: {}
fullObject: {key: value}
integer: 7
string: 'hello World!'
```

This is the expected result and allows me to use `YAML.parse()` to switch back to a JSON object and get the same JSON back just fine. However, if I use `YAML.stringify(data, Infinity, 4);` to expand the YAML as far as it can (which I need for my project since I have a deeply nested JSON object that I am trying to edit in YAML) I get the following:

``` yaml
emptyArray: []
fullArray:
    - 1
    - 2
    - 3
emptyObject:
fullObject:
    key: value
integer: 7
string: 'hello World!'
```

This causes a problem when parsing the YAML back to JSON since the `emptyObject` now parses back to `null` instead of an emptyObject `{}`:

``` json
{
    "emptyArray": [],
    "fullArray": [
        1,
        2,
        3
    ],
    "emptyObject": null,
    "fullObject": {
        "key": "value"
    },
    "integer": 7,
    "string": "hello World!"
}
```

While I realize that the `Infinity` keyword is used in the command to say that all JSON objects should be expanded, the resulting YAML is not equivalent when expanding an empty JSON object. The expected YAML output would be as follows:

``` yaml
emptyArray: []
fullArray:
    - 1
    - 2
    - 3
emptyObject: {}
fullObject:
    key: value
integer: 7
string: 'hello World!'
```
