### ISSUE TITLE
stringify doesn't handle objects depths

### ISSUE THREAD

**Issue by muka** [jeremyfa/yaml.js#66]
Hi,
I'm trying to serialize an object with a certain depth but the result is that yaml is renderer only until the 2nd level of depth while the deeper one are returned as js objects

Does this work as expected?

Example code

```
var obj = {
    a: {
      b: {
        c: true
      }
    },
    b: {
      a: {
        c: false
      }
    }
  };

  console.warn(yamljs.stringify(obj));
```

expected result

```
a:
    b: 
      c: true
b:
    a: 
      c: false
```

actual result

```
a:
    b: {c: true}
b:
    a: {c: false}
```
