### ISSUE TITLE
Barfs on multiple lines

### ISSUE THREAD

**Issue by jmls** [jeremyfa/yaml.js#67]
this yml

```
options:
- list: foo
  url: bar
tasks:
- Task: 5559
  Title: New task
  Description: |
    Added comment....

    Multiple lines

  TaskStatusValue: Not Started
```

parses on http://yaml-online-parser.appspot.com/

but crashes out using yamljs with the error

```
TypeError: vaule.indexOf is not a function
```
