### ISSUE TITLE
Aliases in flow form are not treated as aliases

### ISSUE THREAD

**Issue by janslow** [jeremyfa/yaml.js#74]
# Input
```yaml
foo: &foo
  x: 3

bar1:
  <<: *foo
  y: 3

bar2: {
  <<: *foo,
  y: 3 }
```
[YAML reference parser example](http://ben-kiki.org/ypaste/data/213/index.html)

It also works on [this parser](http://yaml-online-parser.appspot.com/).

# Actual output
```js
> yamljs.parse(`...`)
{ foo: { x: 3 },
  bar1: { x: 3, y: 3 },
  bar2: { '<<': '*foo', y: 3 } }
```

# Expected output
```js
{ foo: { x: 3 },
  bar1: { x: 3, y: 3 },
  bar2: { x: 3, y: 3 } }
```
