### ISSUE TITLE
YAML parse borks data

### ISSUE THREAD

**Issue by jmls** [jeremyfa/yaml.js#84]
given this input

```
server:
  labels:
    port: 6800,8080,3000,9485
    data: name1,name2,name3,name4
```

I get this json:
```
{
  "server": {
    "labels": {
      "port": 68008080,
      "data": "name1,name2,name3,name4"
    }
  }
}
```

which is kinda , inconsistent and wrong ;)

I obviously expected `port` to be `"6800,8080,3000,9485"`

**Comment by jeremyfa** [comment]
Well, that's rather ambiguous as the comma is valid in some notations of numbers (still, I would have expected ``6800808030009485`` in that case, so it would be a good idea to add a test case).

In your situation, I would strongly advise to either use quotes in your yaml, or just use a sequence:

```
server:
  labels:
    port:
      - 6800
      - 8080
      - 3000
      - 9485
```
